// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearUpdateToken() {
  return window['go']['main']['App']['ClearUpdateToken']();
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function EnsureDefaultMemoryBank() {
  return window['go']['main']['App']['EnsureDefaultMemoryBank']();
}

export function GetAPIKey() {
  return window['go']['main']['App']['GetAPIKey']();
}

export function GetSetupStatus() {
  return window['go']['main']['App']['GetSetupStatus']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function InstallCodexHooks() {
  return window['go']['main']['App']['InstallCodexHooks']();
}

export function InstallDownloadedUpdate() {
  return window['go']['main']['App']['InstallDownloadedUpdate']();
}

export function InstallHindsightUI() {
  return window['go']['main']['App']['InstallHindsightUI']();
}

export function InstallOpenCodeMCP() {
  return window['go']['main']['App']['InstallOpenCodeMCP']();
}

export function InstallOpenCodeMCPAt(arg1) {
  return window['go']['main']['App']['InstallOpenCodeMCPAt'](arg1);
}

export function InstallOpenCodePlugin() {
  return window['go']['main']['App']['InstallOpenCodePlugin']();
}

export function InstallOpenCodePluginAt(arg1) {
  return window['go']['main']['App']['InstallOpenCodePluginAt'](arg1);
}

export function ListOpenCodeConfigChoices() {
  return window['go']['main']['App']['ListOpenCodeConfigChoices']();
}

export function ListOpenCodeModels(arg1) {
  return window['go']['main']['App']['ListOpenCodeModels'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenControlPlane() {
  return window['go']['main']['App']['OpenControlPlane']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveUpdateSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveUpdateSettings'](arg1, arg2, arg3);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetTrayManager(arg1) {
  return window['go']['main']['App']['SetTrayManager'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartAll() {
  return window['go']['main']['App']['StartAll']();
}

export function StartBridge() {
  return window['go']['main']['App']['StartBridge']();
}

export function StartControlPlane() {
  return window['go']['main']['App']['StartControlPlane']();
}

export function StartHindsight() {
  return window['go']['main']['App']['StartHindsight']();
}

export function StopAll() {
  return window['go']['main']['App']['StopAll']();
}

export function StopBridge() {
  return window['go']['main']['App']['StopBridge']();
}

export function StopControlPlane() {
  return window['go']['main']['App']['StopControlPlane']();
}

export function StopHindsight() {
  return window['go']['main']['App']['StopHindsight']();
}
