// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelSetup():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateStatus>;

export function ClearUpdateToken():Promise<void>;

export function CopyText(arg1:string):Promise<void>;

export function DownloadUpdate():Promise<main.UpdateStatus>;

export function EnsureDefaultMemoryBank():Promise<void>;

export function GetAPIKey():Promise<string>;

export function GetSetupStatus():Promise<main.SetupStatus>;

export function GetStatus():Promise<main.ManagerStatus>;

export function GetUpdateStatus():Promise<main.UpdateStatus>;

export function HideToTray():Promise<void>;

export function HideWindow():Promise<void>;

export function InstallCodexHooks():Promise<void>;

export function InstallDownloadedUpdate():Promise<void>;

export function InstallHindsightUI():Promise<void>;

export function InstallOpenCodeMCP():Promise<void>;

export function InstallOpenCodeMCPAt(arg1:string):Promise<void>;

export function InstallOpenCodePlugin():Promise<void>;

export function InstallOpenCodePluginAt(arg1:string):Promise<void>;

export function ListOpenCodeConfigChoices():Promise<Array<main.OpenCodeConfigChoice>>;

export function ListOpenCodeModels(arg1:main.BridgeConfig):Promise<Array<string>>;

export function LoadConfig():Promise<main.ManagerConfig>;

export function OpenControlPlane():Promise<void>;

export function QuitApp():Promise<void>;

export function SaveConfig(arg1:main.ManagerConfig):Promise<void>;

export function SaveUpdateSettings(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetTrayManager(arg1:main.TrayManager):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartAll():Promise<void>;

export function StartBridge():Promise<void>;

export function StartControlPlane():Promise<void>;

export function StartHindsight():Promise<void>;

export function StopAll():Promise<void>;

export function StopBridge():Promise<void>;

export function StopControlPlane():Promise<void>;

export function StopHindsight():Promise<void>;
